-- ORCA synthetic seed: Ananya Rao, September 2025 to August 2026.
--
-- GENERATED by scripts/build_ananya_seed.py. Edit the generator, not this file.
--
-- All data is fictional. The shape is the point: this record is uneven, self-
-- contradictory in two places, and silent for ten weeks in the middle. A seed
-- where every month looks alike and everybody agrees would prove nothing about
-- a system built to handle records that do neither.
--
-- The silence between 16 May and 28 July 2026 is the most valuable thing here.
-- It holds exactly three records, all professional, and no self-reports at all.
-- A system that reads fewer entries as fewer problems will report improvement
-- across it. The correct answer is that the trajectory through it is unknown.
--
-- Every record goes through orca_write_record so provenance is enforced rather
-- than assumed, and the sensory-profile correction goes through orca_supersede
-- so is_current and superseded_by cannot disagree.

begin;

delete from outcomes;
delete from strategies;
delete from files;
delete from consents;
delete from record_items where subject_id in (select subject_id from subjects
  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));
delete from stakeholder_relationships where subject_id in (select subject_id from subjects
  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));
delete from subjects where display_name in
  ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer');
delete from users where email like '%@orca.example';

insert into subjects (subject_id, display_name, date_of_birth) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Ananya Rao', '1997-03-14'),
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'Rohan Mehta', '1994-08-02'),
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'Farida Qureshi', '1999-01-27'),
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'Dev Sharma', '1991-11-09'),
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'Neha Iyer', '2001-06-21');

insert into users (user_id, full_name, email, primary_role) values
  ('e0000000-0000-0000-0000-000000000001', 'Ananya Rao', 'ananya@orca.example', 'patient'),
  ('e0000000-0000-0000-0000-000000000002', 'Divya Rao', 'divya@orca.example', 'trusted_person'),
  ('e0000000-0000-0000-0000-000000000003', 'Dr Kavita Nair', 'kavita@orca.example', 'psychologist'),
  ('e0000000-0000-0000-0000-000000000004', 'Dr Arun Deshpande', 'arun@orca.example', 'psychiatrist'),
  ('e0000000-0000-0000-0000-000000000005', 'Sana Kulkarni', 'sana@orca.example', 'ot'),
  ('e0000000-0000-0000-0000-000000000006', 'Meera Joshi', 'meera@orca.example', 'therapist'),
  ('e0000000-0000-0000-0000-000000000007', 'Dr Vikram Rao', 'vikram@orca.example', 'gp'),
  ('e0000000-0000-0000-0000-000000000008', 'Priya Salvi', 'priya@orca.example', 'coordinator'),
  ('e0000000-0000-0000-0000-000000000009', 'Anil Fernandes', 'anil@orca.example', 'employer'),
  ('e0000000-0000-0000-0000-00000000000a', 'Ruth Menon', 'ruth@orca.example', 'university'),
  ('e0000000-0000-0000-0000-00000000000b', 'Tejas Bhatt', 'tejas@orca.example', 'admin');

-- Two dates carry weight. HR gains access only in March 2026, when the
-- accommodation request began, so nothing before that is theirs to read
-- whatever domain it sits in. The accessibility adviser starts in January with
-- the course. A relationship that began in March cannot reach back into
-- December: access here is not retrospective.
insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000002', 'trusted_person', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-10T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000007', 'gp', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'ot', 'support_planning', '2025-10-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000004', 'psychiatrist', 'care', '2025-11-05T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000008', 'coordinator', 'coordination', '2025-12-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'university', 'accommodation', '2026-01-06T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000006', 'therapist', 'support_planning', '2026-02-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'employer', 'accommodation', '2026-03-23T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000b', 'admin', 'coordination', '2025-09-01T00:00:00Z');

-- ------------------------------------------------------------- the year
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Adult autism diagnostic assessment completed at Sahyadri Mind Care and reported to this practice. Recorded on the problem list. No medication indicated at this point.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2025-09-02T09:00:00Z'::timestamptz, 'Diagnosis recorded', 'e0000000-0000-0000-0000-000000000007',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.95, null,
  array['diagnosis']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Being asked something out of nowhere in a meeting. Open plan noise after about two hours. Plans changing on the day. I think I have always been like this but I only have a word for it since June.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-04T09:00:00Z'::timestamptz, 'What I find hard — writing this down properly for once', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['baseline']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Knowing the day before. Writing instead of talking when it is anything complicated. The half hour after I get home where I do not speak to anyone.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-04T09:00:00Z'::timestamptz, 'What actually helps', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['baseline']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Not to be exhausted by Wednesday. That is it really. I do not need anyone to fix anything, I just want to stop losing the rest of the week to the first two days of it.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-05T09:00:00Z'::timestamptz, 'What I want out of this', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['goals']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Ananya has always needed her own time but it is more now, or maybe I am noticing more. She goes straight to her room. I do not want to make it into something it is not.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2025-09-09T09:00:00Z'::timestamptz, 'She is quieter after work than she used to be', 'e0000000-0000-0000-0000-000000000002',
  'low'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'First session. Presenting concerns are workplace sensory load and post-diagnostic adjustment. Good insight into own patterns. Agreed fortnightly sessions and a shared focus on sustainable working weeks rather than symptom reduction.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-09-15T09:00:00Z'::timestamptz, 'Initial psychology session', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Triage call ahead of the sensory assessment. Reports a consistent mid-afternoon deterioration in sustained reading, described as rereading the same passage repeatedly. Onset reported as around 15:00 on most working days.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-09-18T09:00:00Z'::timestamptz, 'Telephone triage before assessment', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  array['sensory']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Second session. Attends on time, prepared, and brings written notes. Reports family contact as supportive but effortful. No concerns regarding risk.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-09-24T09:00:00Z'::timestamptz, 'Session two — early engagement', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.7, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Difficult day. Meeting moved to the morning without warning and I did not recover. Wrote nothing useful after eleven.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-10-03T09:00:00Z'::timestamptz, 'First one of these logs', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Reviewed three recent examples. Common factor is not the change itself but the absence of notice. Distress reported as proportionate to how little warning was given rather than to the size of the change.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-10-08T09:00:00Z'::timestamptz, 'Session — pattern of unplanned change', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Primary sensitivities identified as auditory and, to a lesser extent, tactile. Visual environment reported as neutral. Recommend auditory management as first priority.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-10-12T09:00:00Z'::timestamptz, 'Initial sensory profile', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  array['assessment']::text[], 'f0000000-0000-0000-0000-000000000001');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Kavita suggested a fixed routine in the evening. Same order every night. Feels a bit silly writing it down but I will try it for a month.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-10-16T09:00:00Z'::timestamptz, 'Trying a wind-down thing', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.6, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Could not do the afternoon at all. Sat in the stairwell for twenty minutes. Told them it was a headache.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-10-21T09:00:00Z'::timestamptz, 'Bad one', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Discussed the stairwell episode. Patient reported presenting a physical explanation to colleagues rather than a sensory one. Explored the ongoing cost of that choice without pressing toward disclosure.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-10-22T09:00:00Z'::timestamptz, 'Session — masking cost', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Attended the office. Desk sits within two metres of the main walkway and directly under a ceiling speaker. Ambient level measured as sustained conversational volume with intermittent peaks. Relocation recommended.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-10-29T09:00:00Z'::timestamptz, 'Workplace environment — first walkthrough', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['workplace']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Referred for assessment of co-occurring anxiety. Reported early waking and persistent worry about the working week, present for several months and predating the diagnostic assessment.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2025-11-05T09:00:00Z'::timestamptz, 'Referral to psychiatry', 'e0000000-0000-0000-0000-000000000007',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Assessment completed. Generalised anxiety, moderate, longstanding. No indication of depressive episode. Discussed options including watchful waiting.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2025-11-12T09:00:00Z'::timestamptz, 'Psychiatric assessment', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Co-occurring generalised anxiety. Sertraline 25mg daily commenced, to review at four weeks. Discussed side effect profile including initial increase in agitation.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2025-11-18T09:00:00Z'::timestamptz, 'Medication commenced', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.95, null,
  array['medication']::text[], 'f0000000-0000-0000-0000-000000000002');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Session held two days after commencement. Patient articulate about wanting the anxiety addressed separately from the autism rather than as a consequence of it.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-11-20T09:00:00Z'::timestamptz, 'Session — starting medication', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Wired is the only word for it. Awake at four every morning. They did say this might happen at the start and I am trying to hold onto that.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-11-26T09:00:00Z'::timestamptz, 'Three weeks in and I feel worse', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['medication']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Six weeks of it now. It is not dramatic but I get to bed earlier and I stop checking work things. Keeping it.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-11-27T09:00:00Z'::timestamptz, 'The evening routine is actually fine', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'She said it matter of factly which is how she says things that matter. I did not push. I hope they help her sleep because she is not sleeping.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2025-11-30T09:00:00Z'::timestamptz, 'She told me about the tablets', 'e0000000-0000-0000-0000-000000000002',
  'low'::sensitivity_level, 'unvalidated'::validation_status, 0.45, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Reviewed as planned. Early agitation reported at week three has settled. Sleep onset improved, early waking persists. Continue 25mg and review in eight weeks.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2025-12-02T09:00:00Z'::timestamptz, 'Four week medication review', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  array['medication']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Routine still going. Two months now.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-05T09:00:00Z'::timestamptz, 'Holding so far', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.65, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Cousins arrived Thursday and are here until the new year. There is no quiet room now. I did the evening routine in the car.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-14T09:00:00Z'::timestamptz, 'House full', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Did not sleep. Everyone talks over each other and I cannot follow any of it, and then someone asks me a direct question and I have nothing.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-16T09:00:00Z'::timestamptz, 'Second bad day', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'The house is a lot at the moment. She was fine and then she was not, and she went and sat outside for an hour. I said nothing because she would hate that.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2025-12-17T09:00:00Z'::timestamptz, 'I think it is too much for her', 'e0000000-0000-0000-0000-000000000002',
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Same.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-18T09:00:00Z'::timestamptz, 'Third', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.6, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Got an hour alone in the morning before anyone was up. It made a difference which tells me something I suppose.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-19T09:00:00Z'::timestamptz, 'Slightly better today', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Lost most of Saturday. Could not explain why to anyone who asked and got irritated at being asked.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-21T09:00:00Z'::timestamptz, 'Fourth bad day this week', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'I keep thinking it will settle when the routine comes back and then remembering the routine is the thing that has gone.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-22T09:00:00Z'::timestamptz, 'Still going', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Two weeks of not doing it properly. It was fine when nothing was happening, which is maybe not much of a test.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-23T09:00:00Z'::timestamptz, 'The routine has not survived this', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.8, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Fixed evening wind-down routine recorded as failed. Sustained for nine weeks under stable conditions and abandoned within eleven days of household disruption. The strategy assumed the availability of a quiet space and a predictable evening, which is the condition under which it was least needed.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-12-24T09:00:00Z'::timestamptz, 'Strategy recorded as failed', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'I do not think I am worse. I think everything around me got louder at once. Those are different things and I want to be able to tell them apart.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-27T09:00:00Z'::timestamptz, 'Thinking about the last two weeks', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Reviewed six difficult-day entries logged between the 14th and the 22nd. Patient distinguished clearly between deterioration and environmental load. Formulation agrees. No change to treatment.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-12-29T09:00:00Z'::timestamptz, 'Session — reviewing December', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'They left yesterday. Slept eight hours. First time in three weeks.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-30T09:00:00Z'::timestamptz, 'Quieter now', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['difficult-day']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'education'::record_domain, 'Registered for the part-time postgraduate programme. Disclosure of autism diagnosis received with supporting documentation. Initial meeting scheduled.',
  'professional_reported'::source_type, 'university'::stakeholder_role,
  '2026-01-06T09:00:00Z'::timestamptz, 'Student registered with accessibility service', 'e0000000-0000-0000-0000-00000000000a',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'education'::record_domain, 'Agreed: extended deadlines of five working days on written assessment, recordings of live sessions made available, and advance circulation of session materials where possible. Reviewed at the end of the first semester.',
  'professional_reported'::source_type, 'university'::stakeholder_role,
  '2026-01-08T09:00:00Z'::timestamptz, 'Academic accommodations agreed', 'e0000000-0000-0000-0000-00000000000a',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Psychology, occupational therapy and psychiatry now involved alongside a new academic setting. Circulated a single current summary so that four professionals are not each working from their own version of the last six months.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-01-09T09:00:00Z'::timestamptz, 'Bringing the team into alignment', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'education'::record_domain, 'Two evenings a week and a Saturday morning. Everyone says it is a lot on top of work. It probably is. I wanted something that was mine.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-01-12T09:00:00Z'::timestamptz, 'Started the course', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Discussed load. Patient aware of the risk and has chosen it deliberately rather than by drift. Agreed an explicit review point in March rather than a general caution now.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-01-15T09:00:00Z'::timestamptz, 'Session — capacity and the new course', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Mapped the week with Ananya. Tuesday and Thursday now run from 09:00 to approximately 21:30 including travel and the evening session. Friday consistently reported as the lowest-capacity day.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-01-19T09:00:00Z'::timestamptz, 'Load mapping across the working week', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'education'::record_domain, 'Session recordings confirmed as available for all four modules. Student reports the primary benefit as removing the need to capture everything at first hearing.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-01-22T09:00:00Z'::timestamptz, 'Accommodation check — first month', 'e0000000-0000-0000-0000-000000000008',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Agreed review points with each service so that the March review is a shared one rather than four separate conversations. Ananya asked to be present at all of them.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-01-26T09:00:00Z'::timestamptz, 'Coordination note — review cadence set', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Reported fatigue now clusters on Wednesday and Friday rather than Friday alone, coinciding with the two long days. Consistent with cumulative rather than acute load.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-01-29T09:00:00Z'::timestamptz, 'Interim check — fatigue pattern', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Referred for workplace communication. Initial focus on unplanned verbal exchanges: being asked for a view without notice, and closing a conversation without it reading as abrupt.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-02-03T09:00:00Z'::timestamptz, 'Speech and communication therapy commenced', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Mornings have been okay for a few weeks now. I get out of the house on time most days and it does not feel like the effort it used to.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-02-08T09:00:00Z'::timestamptz, 'Mornings manageable at present', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  null, 'f0000000-0000-0000-0000-000000000003');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Across entries from January and February 2026, the course is described in terms of written materials and stated expectations, while the workplace is described in terms of unplanned verbal exchanges. This is a difference in how the two settings are written about, not a measured comparison between them.',
  'ai_derived'::source_type, 'system'::stakeholder_role,
  '2026-02-10T09:00:00Z'::timestamptz, 'Entries describe the academic setting as more predictable than work', null,
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.35, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Practised three prepared responses for being asked something without warning. Patient reports the value is less in the wording than in not having to compose anything in the moment.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-02-12T09:00:00Z'::timestamptz, 'Session two — holding phrases', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Metro is busier since January. Or I am less able for it. Hard to say which.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-02-16T09:00:00Z'::timestamptz, 'The commute is getting worse though', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.65, null,
  array['sensory']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Home visit at 08:15. Observed prolonged difficulty initiating departure, three returns to the flat for forgotten items, and visible distress at the delay. Duration from first attempt to leaving was 34 minutes.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-02-21T09:00:00Z'::timestamptz, 'Observed significant difficulty with morning departure', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  null, 'f0000000-0000-0000-0000-000000000004');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Reviewed one live use of a prepared response at work. Reported as successful in the moment and exhausting afterwards. Both recorded; the second does not cancel the first.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-02-24T09:00:00Z'::timestamptz, 'Session three', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Reported using a prepared response in a meeting without it being noticed by colleagues. Recorded as the intended outcome: the strategy is meant to be invisible to everyone except the person using it.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-02-25T09:00:00Z'::timestamptz, 'Session four — first live use', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Both the patient''s account of manageable mornings and the occupational therapist''s home visit observation are on the record and neither has been amended. Discussed openly. Patient''s view is that both are true and that she had stopped counting the departure itself as difficulty.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-27T09:00:00Z'::timestamptz, 'Session — two accounts of the mornings', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Too many people and I missed it and had to come back. Then I was late and had to explain being late.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-03-02T09:00:00Z'::timestamptz, 'Could not get off at my stop', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['sensory','commute']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Same thing. I am starting to leave earlier to get a quieter train which means getting up at half five.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-03-04T09:00:00Z'::timestamptz, 'Again on Wednesday', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  array['commute']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Agreed to prepare a formal accommodation request. Scope limited to what the employer needs in order to act: functional effect and the adjustment sought. No diagnostic or clinical detail to be included.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-03-06T09:00:00Z'::timestamptz, 'Preparing a workplace request', 'e0000000-0000-0000-0000-000000000008',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Asked for a quieter desk, written instructions, and starting at ten. Writing it down made it look reasonable which it did not feel like beforehand.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-03-10T09:00:00Z'::timestamptz, 'Sent the request', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Revised following six months of observation. Auditory sensitivity confirmed as primary. Visual sensitivity now assessed as significant under fluorescent lighting, previously missed. Tactile sensitivity assessed as minor. Auditory management alone is insufficient.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-03-15T09:00:00Z'::timestamptz, 'Sensory profile — revised', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  array['assessment']::text[], 'f0000000-0000-0000-0000-000000000005');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Rehearsed the follow-up conversation with the line manager. Focus on asking once, in writing, with a stated date.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-03-17T09:00:00Z'::timestamptz, 'Session — asking for something at work', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'The review agreed in January. Course load sustainable. Commute now the dominant stressor, ahead of the working day itself.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-19T09:00:00Z'::timestamptz, 'Session — March review point', 'e0000000-0000-0000-0000-000000000003',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Request logged and acknowledged. Referred to occupational health for review. Response due within fifteen working days per policy.',
  'professional_reported'::source_type, 'employer'::stakeholder_role,
  '2026-03-23T09:00:00Z'::timestamptz, 'Accommodation request received', 'e0000000-0000-0000-0000-000000000009',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'No response yet from the employer at fifteen days. Ananya has not chased it, citing reluctance to be seen as difficult. Recorded because the delay itself is now affecting the working week.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-03-26T09:00:00Z'::timestamptz, 'Interim note — request pending', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Earlier train is genuinely quieter. Costs me an hour of sleep. Net positive I think, ask me in a month.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-03-30T09:00:00Z'::timestamptz, 'Leaving at half six now', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.65, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Submitted supporting recommendations: relocation away from the walkway and out of direct fluorescent lighting, written confirmation of task changes, and a staggered start to avoid peak crowding.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-04-02T09:00:00Z'::timestamptz, 'Recommendations to occupational health', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'By the window now, away from the walkway. Immediately better. I did not realise how much of it was people passing behind me.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-04-07T09:00:00Z'::timestamptz, 'Desk has moved', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Reports a clear improvement in sustained attention since relocation. Notes that this was the adjustment requiring least of anyone else.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-09T09:00:00Z'::timestamptz, 'Session — after the desk move', 'e0000000-0000-0000-0000-000000000003',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'All three agreed adjustments now in place: relocated desk away from the walkway, written task instructions from line manager, and staggered start time of 10:00.',
  'professional_reported'::source_type, 'employer'::stakeholder_role,
  '2026-04-14T09:00:00Z'::timestamptz, 'Workplace adjustments implemented', 'e0000000-0000-0000-0000-000000000009',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, 'f0000000-0000-0000-0000-000000000006');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Reviewed the written-instruction adjustment. Patient reports it has not begun. Agreed wording for a single follow-up request.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-04-16T09:00:00Z'::timestamptz, 'Session five', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Brief telephone contact. Reports four weeks of increasing fatigue. No new physical symptoms. Advised to attend in person if unchanged in a fortnight.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-04-20T09:00:00Z'::timestamptz, 'Telephone contact — fatigue', 'e0000000-0000-0000-0000-000000000007',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Not the usual after-work tired. She cancelled Sunday which she never does. She said it is fine and work is sorted now.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2026-04-23T09:00:00Z'::timestamptz, 'She is tired in a different way', 'e0000000-0000-0000-0000-000000000002',
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Attended for medication review. Reports increasing fatigue over four weeks. Sleep adequate in duration. Advised to return if this continues.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-04-27T09:00:00Z'::timestamptz, 'Routine review', 'e0000000-0000-0000-0000-000000000007',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'The desk moved and that has helped. I have not received written instructions from my manager at any point. Start time is still 09:00 and nobody has mentioned changing it. Not sure who to ask without it becoming a thing.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-04-29T09:00:00Z'::timestamptz, 'Written instructions have not started', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.8, null,
  null, 'f0000000-0000-0000-0000-000000000007');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Every day takes everything and there is none left for the next one. Four weeks of this now.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-04-30T09:00:00Z'::timestamptz, 'Running on nothing', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Could not do it. Said I was ill. I was not ill exactly.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-05-02T09:00:00Z'::timestamptz, 'Missed Friday', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Marked change since the April session. Reports reduced tolerance for the commute and for unplanned interaction. Discussed the gap between the adjustments recorded as implemented and those the patient reports as active.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-05T09:00:00Z'::timestamptz, 'Session — deterioration noted', 'e0000000-0000-0000-0000-000000000003',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Contacted between reviews reporting a marked drop in capacity with no identifiable trigger. Discussed and no dose change made. Advised that an absent trigger does not make the deterioration less real.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2026-05-07T09:00:00Z'::timestamptz, 'Unscheduled contact', 'e0000000-0000-0000-0000-000000000004',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'The quiet train was working and now it is not, and I think that is because I have nothing left to spend rather than because the train changed.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Earlier train is not helping now', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Second absence this month, both at the point of travel rather than at work. Reassessed the commute as the current limiting factor rather than the working environment, which was the position in March.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-05-11T09:00:00Z'::timestamptz, 'Commute tolerance — reassessment', 'e0000000-0000-0000-0000-000000000005',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Attended reporting exhaustion, two absences this month and inability to sustain the commute. Presentation consistent with autistic burnout rather than a depressive episode. Two weeks of medical leave certified, with phased return to be agreed.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-05-13T09:00:00Z'::timestamptz, 'Consultation — fitness for work', 'e0000000-0000-0000-0000-000000000007',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Two weeks certified from the 15th. Psychology, occupational therapy and the university notified with Ananya''s agreement. Employer informed of absence only, without clinical detail.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-05-14T09:00:00Z'::timestamptz, 'Leave arranged and services notified', 'e0000000-0000-0000-0000-000000000007',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Cannot face the commute. Missed two days. Everything is loud and I am not managing conversations at work. Sleeping badly. I do not want to write these entries at the moment.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-05-16T09:00:00Z'::timestamptz, 'Worst week so far', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.8, null,
  null, 'f0000000-0000-0000-0000-000000000008');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Reviewed in the context of certified leave. Presentation attributed to sustained environmental load rather than a change in anxiety. No dose change made; increasing medication would treat the wrong thing.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2026-06-04T09:00:00Z'::timestamptz, 'Medication review during leave', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null,
  array['medication']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Reports some improvement in sleep. Not yet fit for full duties. Leave extended and phased return discussed for late July.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-06-19T09:00:00Z'::timestamptz, 'Follow-up and extension of leave', 'e0000000-0000-0000-0000-000000000007',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Recorded explicitly: Ananya has not logged an entry since 16 May. Professional contact has continued. The absence of entries is an absence of reporting and must not be read as an absence of difficulty.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-06-27T09:00:00Z'::timestamptz, 'Coordination note — no self-reported data since 16 May', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['gap']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Back at work three days a week since the 21st. Have not written anything here for a while. Some days have been fine and some have not, but I stopped keeping track of which.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-07-28T09:00:00Z'::timestamptz, 'Starting to log again', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, 'f0000000-0000-0000-0000-000000000009');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'First review since the phased return began. Sleep and appetite settled. Continue current dose through the return period and review in three months.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2026-07-29T09:00:00Z'::timestamptz, 'Review on return to work', 'e0000000-0000-0000-0000-000000000004',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.8, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'First session since 5 May. Reviewed what is known about the intervening period, which is little: three professional contacts and no self-report. Agreed not to reconstruct the gap retrospectively.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-30T09:00:00Z'::timestamptz, 'Session — first since the return', 'e0000000-0000-0000-0000-000000000003',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  array['session']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Tuesday Wednesday Thursday. Long weekends both sides. It is the first arrangement in a year that has not felt like managing.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-07-30T09:00:00Z'::timestamptz, 'Three days is about right', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.7, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Attended on the second week of phased return. Desk position retained from March. Fluorescent lighting above the new position replaced with a diffused fitting following the revised profile.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-07-31T09:00:00Z'::timestamptz, 'Phased return — environmental review', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.85, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Not what I expected. Taking them off was an immediate relief which tells me enough. Stopping.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-08-04T09:00:00Z'::timestamptz, 'The headphones made it worse', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.8, null,
  array['strategy']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Four months after they said it was in place. It is a completely different journey. I am not going to be gracious about how long it took but it is working.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-08-14T09:00:00Z'::timestamptz, 'Ten o''clock start is actually happening', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.8, null,
  null, null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Across entries from February to April 2026, difficulty on the morning commute was reported more often on days following a recorded late finish. This is a pattern in the record, not a confirmed relationship, and the May to July gap means it has not been tested since.',
  'ai_derived'::source_type, 'system'::stakeholder_role,
  '2026-08-20T09:00:00Z'::timestamptz, 'Possible association between late finishes and next-day commute difficulty', null,
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.35, null,
  array['pattern']::text[], 'f0000000-0000-0000-0000-00000000000a');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Self-reported entries are running at roughly the rate recorded before 16 May. This describes how much is being written, not how things are. The period between 16 May and 28 July contains no self-reports at all and nothing here can characterise it.',
  'ai_derived'::source_type, 'system'::stakeholder_role,
  '2026-08-22T09:00:00Z'::timestamptz, 'Reporting frequency has returned to its pre-May level', null,
  'low'::sensitivity_level, 'unvalidated'::validation_status, 0.3, null,
  array['pattern','gap']::text[], null);
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Better than March. I can say that much. What happened between May and July I genuinely could not tell you and I would rather say that than make something up.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-08-26T09:00:00Z'::timestamptz, 'Where I am now', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null,
  null, null);

-- The correction, through orca_supersede rather than three hand-written
-- updates, so both links and both is_current flags are set together or not at
-- all. The October profile stays readable: it was not wrong when it was
-- written, it was the best reading available after one assessment, and a
-- record that quietly loses its earlier version cannot show anyone how the
-- understanding actually developed.
select orca_supersede('f0000000-0000-0000-0000-000000000001',
                      'f0000000-0000-0000-0000-000000000005');

-- 9 strategies: 3 worked, 3 partial, 2 failed, 1 still running. A seed where
-- everything worked would train a planner to be confident about advice that
-- has never survived contact with a bad week.
insert into strategies (strategy_id, subject_id, title, description, proposed_by, proposer_role, domain, started_on, ended_on, state) values
  ('b0000000-0000-0000-0000-000000000001', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Fixed evening wind-down routine', 'Same sequence every evening: no screens after 21:30, reading, lights out at 22:30.', 'e0000000-0000-0000-0000-000000000001', 'patient', 'support'::record_domain, '2025-10-16', '2025-12-23', 'failed'),
  ('b0000000-0000-0000-0000-000000000002', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Written advance notice of schedule changes', 'Any change to the day communicated in writing, ideally the day before.', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'support'::record_domain, '2025-11-04', null, 'running'),
  ('b0000000-0000-0000-0000-000000000003', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Session recordings for the course', 'Recordings of live sessions made available so nothing depends on capturing it first time.', 'e0000000-0000-0000-0000-00000000000a', 'university', 'education'::record_domain, '2026-01-08', '2026-06-30', 'worked'),
  ('b0000000-0000-0000-0000-000000000004', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Prepared responses for unplanned questions', 'Three rehearsed phrases for being asked for a view without notice.', 'e0000000-0000-0000-0000-000000000006', 'therapist', 'support'::record_domain, '2026-02-12', '2026-08-01', 'worked'),
  ('b0000000-0000-0000-0000-000000000005', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Earlier train to avoid peak crowding', 'Leaving at 06:30 for a quieter carriage.', 'e0000000-0000-0000-0000-000000000001', 'patient', 'functional'::record_domain, '2026-03-30', '2026-05-13', 'partial'),
  ('b0000000-0000-0000-0000-000000000006', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Desk relocation away from the walkway', 'Move out of the walkway and out from under the ceiling speaker.', 'e0000000-0000-0000-0000-000000000005', 'ot', 'workplace'::record_domain, '2026-04-07', null, 'worked'),
  ('b0000000-0000-0000-0000-000000000007', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Written task instructions from the line manager', 'Task changes confirmed in writing rather than in passing.', 'e0000000-0000-0000-0000-000000000005', 'ot', 'workplace'::record_domain, '2026-04-14', '2026-08-14', 'partial'),
  ('b0000000-0000-0000-0000-000000000008', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Noise-cancelling headphones for the full commute', 'Noise-cancelling headphones for the full commute', 'e0000000-0000-0000-0000-000000000001', 'patient', 'functional'::record_domain, '2026-07-30', '2026-08-11', 'failed'),
  ('b0000000-0000-0000-0000-000000000009', 'aaaaaaaa-0000-0000-0000-00000000000a', 'Staggered start at 10:00', 'Start at 10:00 to travel after the peak.', 'e0000000-0000-0000-0000-000000000009', 'employer', 'workplace'::record_domain, '2026-08-11', null, 'worked');

-- 14 outcomes, and never all reported by the subject. A record in which only
-- the person themselves ever says whether something helped is a record that
-- has quietly made them responsible for evaluating their own support.
insert into outcomes (strategy_id, subject_id, reported_by, reporter_role, reported_on, effectiveness, what_worked, what_did_not_work, context) values
  ('b0000000-0000-0000-0000-000000000001', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2025-11-27', 'worked', 'Getting to bed earlier and stopping checking work things.', null, 'Stable weeks, nothing unusual at home.'),
  ('b0000000-0000-0000-0000-000000000001', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2025-12-23', 'made_worse', null, 'Could not be done at all once the house was full. The routine needed a quiet evening, which is the condition under which it was least needed.', 'Twelve visitors over the festival period.'),
  ('b0000000-0000-0000-0000-000000000001', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'psychologist'::stakeholder_role, '2025-12-24', 'no_benefit', null, 'Sustained nine weeks under stable conditions and abandoned within eleven days of disruption.', 'Recorded at the December review.'),
  ('b0000000-0000-0000-0000-000000000002', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-01-19', 'partial', 'When it happens it makes the difference between a hard morning and a lost day.', 'It does not happen reliably.', 'Work.'),
  ('b0000000-0000-0000-0000-000000000002', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'psychologist'::stakeholder_role, '2026-03-19', 'partial', 'Consistently effective where applied.', 'Application is inconsistent and outside the patient control.', 'March review point.'),
  ('b0000000-0000-0000-0000-000000000003', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'university'::stakeholder_role, '2026-02-01', 'worked', 'Used for all four modules. Student reports it removes the need to capture everything at first hearing.', null, 'First month of the course.'),
  ('b0000000-0000-0000-0000-000000000003', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-06-30', 'worked', 'The one adjustment I never had to chase.', null, 'End of first semester.'),
  ('b0000000-0000-0000-0000-000000000004', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000006', 'therapist'::stakeholder_role, '2026-02-24', 'partial', 'Successful in the live exchange.', 'Reported as exhausting afterwards. Both are true and the second does not cancel the first.', 'Workplace meeting.'),
  ('b0000000-0000-0000-0000-000000000004', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-08-01', 'worked', 'I use them without thinking about it now.', null, 'Six months in.'),
  ('b0000000-0000-0000-0000-000000000005', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-05-09', 'made_worse', 'It was working in March.', 'By May the hour of sleep cost more than the quiet carriage gave back. The train did not change; what I had to spend did.', 'Peak-hour Pune Metro.'),
  ('b0000000-0000-0000-0000-000000000006', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'ot'::stakeholder_role, '2026-04-07', 'worked', 'Immediate improvement in sustained attention. The adjustment requiring least of anyone else.', null, 'Office walkthrough follow-up.'),
  ('b0000000-0000-0000-0000-000000000007', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'employer'::stakeholder_role, '2026-04-14', 'worked', 'Recorded as implemented alongside the other two adjustments.', null, 'HR administrative record.'),
  ('b0000000-0000-0000-0000-000000000007', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-04-29', 'no_benefit', 'The desk move helped.', 'Written instructions never actually started. Asked twice. Still told things in the corridor.', 'Four months after it was agreed.'),
  ('b0000000-0000-0000-0000-000000000008', 'aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient'::stakeholder_role, '2026-08-11', 'made_worse', null, 'Removing ambient sound made it harder to judge distance and crowd movement. Felt more disoriented on the platform, not less. Two near-misses on the stairs.', 'Peak-hour Pune Metro, standing.');

-- Files: metadata only. contents_read stays false because nothing has parsed
-- them, and a file row that implies otherwise is an invented finding in a
-- different costume.
insert into files (subject_id, title, kind, domain, sensitivity, uploaded_by, uploader_role, occurred_on, contents_read) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'OT initial sensory assessment', 'assessment', 'functional'::record_domain, 'moderate'::sensitivity_level, 'e0000000-0000-0000-0000-000000000005', 'ot', '2025-10-12', false),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Psychiatry letter to GP', 'letter', 'clinical'::record_domain, 'restricted'::sensitivity_level, 'e0000000-0000-0000-0000-000000000004', 'psychiatrist', '2025-11-19', false),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Course accommodation plan', 'plan', 'education'::record_domain, 'low'::sensitivity_level, 'e0000000-0000-0000-0000-00000000000a', 'university', '2026-01-08', false),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Workplace accommodation request', 'request', 'workplace'::record_domain, 'moderate'::sensitivity_level, 'e0000000-0000-0000-0000-000000000008', 'coordinator', '2026-03-10', false),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Fit note — two weeks', 'certificate', 'clinical'::record_domain, 'high'::sensitivity_level, 'e0000000-0000-0000-0000-000000000007', 'gp', '2026-05-13', false),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Phased return plan', 'plan', 'workplace'::record_domain, 'low'::sensitivity_level, 'e0000000-0000-0000-0000-000000000009', 'employer', '2026-07-21', false);

-- Consents, with the dates that make the access model testable.
insert into consents (subject_id, user_id, domain, purpose, granted_on) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'clinical'::record_domain, 'care'::purpose_type, '2025-09-10'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000004', 'clinical'::record_domain, 'care'::purpose_type, '2025-11-05'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'functional'::record_domain, 'support_planning'::purpose_type, '2025-10-01'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'education'::record_domain, 'accommodation'::purpose_type, '2026-01-06'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'workplace'::record_domain, 'accommodation'::purpose_type, '2026-03-23');

-- The other four on Dr Nair's caseload. Deliberately thin: they exist so the
-- psychologist has a real list and so cross-subject access can be tested, not
-- to be read.
insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'functional'::record_domain,
  'Routine entry 1 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-05T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'personal'::record_domain,
  'Routine entry 2 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-06T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'support'::record_domain,
  'Routine entry 3 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-07T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'clinical'::record_domain,
  'Routine entry 4 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-08T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'functional'::record_domain,
  'Routine entry 5 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-09T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'support'::record_domain,
  'Routine entry 6 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-10T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'personal'::record_domain,
  'Routine entry 7 for Rohan Mehta. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-08-11T09:00:00Z'::timestamptz, 'Caseload note 7', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'functional'::record_domain,
  'Routine entry 1 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-05T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'personal'::record_domain,
  'Routine entry 2 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-06T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'support'::record_domain,
  'Routine entry 3 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-07T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'clinical'::record_domain,
  'Routine entry 4 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-08T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'functional'::record_domain,
  'Routine entry 5 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-09T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'support'::record_domain,
  'Routine entry 6 for Farida Qureshi. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-10T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'functional'::record_domain,
  'Routine entry 1 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-05T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'personal'::record_domain,
  'Routine entry 2 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-06T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'support'::record_domain,
  'Routine entry 3 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-07T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'clinical'::record_domain,
  'Routine entry 4 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-08T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'functional'::record_domain,
  'Routine entry 5 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-09T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'support'::record_domain,
  'Routine entry 6 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-10T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'personal'::record_domain,
  'Routine entry 7 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-08-11T09:00:00Z'::timestamptz, 'Caseload note 7', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'functional'::record_domain,
  'Routine entry 8 for Dev Sharma. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-08-12T09:00:00Z'::timestamptz, 'Caseload note 8', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'functional'::record_domain,
  'Routine entry 1 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-05T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'personal'::record_domain,
  'Routine entry 2 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-06T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'support'::record_domain,
  'Routine entry 3 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-07T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'clinical'::record_domain,
  'Routine entry 4 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-08T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'functional'::record_domain,
  'Routine entry 5 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-09T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'support'::record_domain,
  'Routine entry 6 for Neha Iyer. Placeholder content for caseload testing.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-10T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

commit;
