-- Ananya Rao — longitudinal record extract, seeded verbatim.
--
-- GENERATED by scripts/build_record_set.py from the authoritative extract.
-- Edit the extract and regenerate; do not edit this file.
--
-- 41 records, September 2025 to August 2026. All fictional.
--
-- The build refuses to emit unless every [Rnnn] in the source is parsed. The
-- first parser written for it dropped R007 and R024 — the two carrying the
-- supersession chain, because they have a fourth pipe-delimited field — and
-- would have produced a seed that looked complete and was missing exactly
-- the records the dataset exists to demonstrate.
--
-- Relationship dates bind: the roster below is what makes an employer unable
-- to read anything before March 2026, whatever domain it sits in.

begin;

delete from context_briefs where subject_id = 'aaaaaaaa-0000-0000-0000-00000000000a';
delete from agents_run where run_id in (select run_id from runs where subject_id = 'aaaaaaaa-0000-0000-0000-00000000000a');
delete from support_outcomes; delete from support_strategies;
delete from files; delete from consents;
delete from record_items where subject_id in (select subject_id from subjects
  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));
delete from stakeholder_relationships where subject_id in (select subject_id from subjects
  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));
delete from subjects where display_name in
  ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer');
delete from users where email like '%@orca.example';

insert into subjects (subject_id, display_name, date_of_birth) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'Ananya Rao', '1997-03-14'),
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'Rohan Mehta', '1994-08-02'),
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'Farida Qureshi', '1999-01-27'),
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'Dev Sharma', '1991-11-09'),
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'Neha Iyer', '2001-06-21');

insert into users (user_id, full_name, email, primary_role) values
  ('e0000000-0000-0000-0000-000000000001', 'Ananya Rao', 'ananya.rao@orca.example', 'patient'),
  ('e0000000-0000-0000-0000-000000000002', 'Divya Rao', 'divya.rao@orca.example', 'trusted_person'),
  ('e0000000-0000-0000-0000-000000000003', 'Dr Kavita Nair', 'kavita.nair@orca.example', 'psychologist'),
  ('e0000000-0000-0000-0000-000000000004', 'Dr Arun Deshpande', 'arun.deshpande@orca.example', 'psychiatrist'),
  ('e0000000-0000-0000-0000-000000000005', 'Sana Kulkarni', 'sana.kulkarni@orca.example', 'ot'),
  ('e0000000-0000-0000-0000-000000000006', 'Meera Joshi', 'meera.joshi@orca.example', 'therapist'),
  ('e0000000-0000-0000-0000-000000000007', 'Dr Vikram Rao', 'vikram.rao@orca.example', 'gp'),
  ('e0000000-0000-0000-0000-000000000008', 'Priya Salvi', 'priya.salvi@orca.example', 'coordinator'),
  ('e0000000-0000-0000-0000-000000000009', 'Anil Fernandes', 'anil.fernandes@orca.example', 'employer'),
  ('e0000000-0000-0000-0000-00000000000a', 'Ruth Menon', 'ruth.menon@orca.example', 'university'),
  ('e0000000-0000-0000-0000-00000000000b', 'Tejas Bhatt', 'tejas.bhatt@orca.example', 'admin');

-- Valid-from dates taken from the roster. These are not decoration: they are
-- the floor orca_access_floor applies, and they are why Meera Joshi cannot
-- see anything before February 2026 and Anil Fernandes nothing before March.
insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000002', 'trusted_person', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000007', 'gp', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000b', 'admin', 'coordination', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-15T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'ot', 'support_planning', '2025-10-05T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000004', 'psychiatrist', 'care', '2025-11-10T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000008', 'coordinator', 'coordination', '2025-12-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'university', 'accommodation', '2026-01-05T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000006', 'therapist', 'support_planning', '2026-02-10T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'employer', 'accommodation', '2026-03-01T00:00:00Z');

-- Consents C1–C7, as filed. None withdrawn.
insert into consents (subject_id, user_id, domain, purpose, granted_on) values
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'clinical'::record_domain, 'care'::purpose_type, '2025-09-15'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'functional'::record_domain, 'care'::purpose_type, '2025-09-15'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'personal'::record_domain, 'care'::purpose_type, '2025-09-15'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000003', 'support'::record_domain, 'care'::purpose_type, '2025-09-15'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000004', 'clinical'::record_domain, 'care'::purpose_type, '2025-11-10'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000004', 'functional'::record_domain, 'care'::purpose_type, '2025-11-10'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'functional'::record_domain, 'support_planning'::purpose_type, '2025-10-05'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000005', 'support'::record_domain, 'support_planning'::purpose_type, '2025-10-05'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000006', 'functional'::record_domain, 'support_planning'::purpose_type, '2026-02-10'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000006', 'support'::record_domain, 'support_planning'::purpose_type, '2026-02-10'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000002', 'personal'::record_domain, 'personal_understanding'::purpose_type, '2025-09-01'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000002', 'support'::record_domain, 'personal_understanding'::purpose_type, '2025-09-01'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'education'::record_domain, 'accommodation'::purpose_type, '2026-01-05'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-00000000000a', 'functional'::record_domain, 'accommodation'::purpose_type, '2026-01-05'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'workplace'::record_domain, 'accommodation'::purpose_type, '2026-03-01'),
  ('aaaaaaaa-0000-0000-0000-00000000000a', 'e0000000-0000-0000-0000-000000000009', 'functional'::record_domain, 'accommodation'::purpose_type, '2026-03-01');

-- ------------------------------------------------------ the 41 records
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Formal diagnosis of autism spectrum condition confirmed following adult assessment pathway. Age at diagnosis 28. Referred to clinical psychology for post-diagnostic support.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2025-09-03T09:00:00Z'::timestamptz, 'Autism diagnosis recorded', 'e0000000-0000-0000-0000-000000000007',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000001');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'I want to stop feeling like I am failing at things other people find easy. Mostly I want to understand why some days are fine and some days are not. I do not want to be managed.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-05T09:00:00Z'::timestamptz, 'What I want from this', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000002');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Noise in open offices. Being interrupted when I am mid-task. Phone calls with no warning. Unfamiliar routes. Small talk, though I have got better at faking it.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-05T09:00:00Z'::timestamptz, 'Things I find hard', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000003');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Knowing the plan in advance. Writing things down. Leaving early so I am not rushed. Having somewhere quiet to go at lunch.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-09-05T09:00:00Z'::timestamptz, 'Things that already help', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000004');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'She has always needed more recovery time than she admits. After family events she goes quiet for two or three days. I do not think she notices the pattern herself.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2025-09-11T09:00:00Z'::timestamptz, 'Observation from Divya', 'e0000000-0000-0000-0000-000000000002',
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null, null, 'f0000000-0000-0000-0000-000000000005');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'First post-diagnostic session. Presentation consistent with late-diagnosed autism in an adult with strong compensatory strategies. Reports long-standing masking at work. Fortnightly sessions agreed.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2025-09-19T09:00:00Z'::timestamptz, 'Initial psychology session', 'e0000000-0000-0000-0000-000000000003',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000006');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Primary sensitivities identified as auditory and, to a lesser extent, tactile. Visual environment reported as neutral. Recommend auditory management as first priority.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-10-12T09:00:00Z'::timestamptz, 'Initial sensory profile', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'outdated'::validation_status, 0.4, null, null, 'f0000000-0000-0000-0000-000000000007');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Structured 45-minute wind-down proposed: fixed sequence, no screens in final 20 minutes, same order each evening. Aim is to reduce next-day depletion.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-10-17T09:00:00Z'::timestamptz, 'Evening wind-down routine proposed', 'e0000000-0000-0000-0000-000000000005',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000008');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Three unplanned meetings. By 4pm I could not follow what anyone was saying. Went home and did not speak for the rest of the evening.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-10-24T09:00:00Z'::timestamptz, 'Difficult day', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000009');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Quiet week at work, no surprises. Managed the wind-down thing most nights. Felt roughly normal, whatever that means.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-10-30T09:00:00Z'::timestamptz, 'Good week', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000010');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Co-occurring generalised anxiety. Sertraline 25mg daily commenced, to review at four weeks. Discussed side effect profile including initial increase in agitation.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2025-11-18T09:00:00Z'::timestamptz, 'Medication commenced', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000011');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Jaw tension and worse sleep since starting. Told Dr Deshpande. He says give it another fortnight. I am not sure I can tell what is the medication and what is just November.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-11-29T09:00:00Z'::timestamptz, 'Side effects week three', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000012');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Visitors since the 9th. No wind-down, no quiet room, no predictable anything. Fourth bad day in a row.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-14T09:00:00Z'::timestamptz, 'Routine has gone', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000013');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'She managed the whole day and was lovely with everyone. She did disappear for an hour in the afternoon but she seemed fine to me. I think she is doing better than she thinks.',
  'self_reported'::source_type, 'trusted_person'::stakeholder_role,
  '2025-12-16T09:00:00Z'::timestamptz, 'Family gathering', 'e0000000-0000-0000-0000-000000000002',
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null, null, 'f0000000-0000-0000-0000-000000000014');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Got through it by leaving for an hour and sitting in the car. Everyone said I did well. I could not read for two days afterwards.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-16T09:00:00Z'::timestamptz, 'Same day, from my side', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000015');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Strategy did not hold under disruption. Abandoned during visitor period and not resumed. Recorded as failed under variable conditions rather than failed outright.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2025-12-22T09:00:00Z'::timestamptz, 'Wind-down routine — outcome recorded', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000016');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Counting them now because Dr Nair asked me to. Six since the 9th. Before that maybe one a fortnight.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2025-12-28T09:00:00Z'::timestamptz, 'Sixth bad day this month', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000017');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'education'::record_domain, 'Part-time postgraduate enrolment confirmed. Agreed: extended assignment deadlines by ten working days, session recordings provided, alternative to group presentation assessment.',
  'professional_reported'::source_type, 'university'::stakeholder_role,
  '2026-01-08T09:00:00Z'::timestamptz, 'Course accommodations agreed', 'e0000000-0000-0000-0000-00000000000a',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000018');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Psychology, OT and psychiatry now working to a shared formulation. Agreed priority for Q1: workplace environment rather than clinical intervention.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-01-15T09:00:00Z'::timestamptz, 'Multi-professional alignment', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000019');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'personal'::record_domain, 'Recordings help more than the deadlines do. I can listen again at 2am when it is quiet and it actually goes in.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-01-27T09:00:00Z'::timestamptz, 'Course is going okay', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000020');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Mornings have been okay for a few weeks now. I get out of the house on time most days and it does not feel like the effort it used to.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-02-08T09:00:00Z'::timestamptz, 'Mornings manageable at present', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000021');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Focus on workplace conversations: requesting clarification without apology, ending interactions, and scripting for unplanned phone calls.',
  'professional_reported'::source_type, 'therapist'::stakeholder_role,
  '2026-02-14T09:00:00Z'::timestamptz, 'Communication work commenced', 'e0000000-0000-0000-0000-000000000006',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000022');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Home visit at 08:15. Observed prolonged difficulty initiating departure, three returns to the flat for forgotten items, and visible distress at the delay. Duration from first attempt to leaving was 34 minutes.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-02-21T09:00:00Z'::timestamptz, 'Observed significant difficulty with morning departure', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000023');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Revised following six months of observation. Auditory sensitivity confirmed as primary. Visual sensitivity now assessed as significant under fluorescent lighting, previously missed. Tactile sensitivity assessed as minor. Auditory management alone is insufficient.',
  'professional_reported'::source_type, 'ot'::stakeholder_role,
  '2026-03-15T09:00:00Z'::timestamptz, 'Sensory profile — revised', 'e0000000-0000-0000-0000-000000000005',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000024');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Metro at 8:40 is unbearable now. It is not just the noise, it is the lighting in the carriage. Arrived at work already finished twice this week.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-03-19T09:00:00Z'::timestamptz, 'Commute is getting worse', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000025');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Request prepared for employer covering three adjustments: relocated desk away from the main walkway, written task instructions from line manager, staggered start time of 10:00. Clinical detail excluded; functional impact only.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-03-26T09:00:00Z'::timestamptz, 'Accommodation request prepared', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000026');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'All three agreed adjustments now in place: relocated desk away from the walkway, written task instructions from line manager, and staggered start time of 10:00.',
  'professional_reported'::source_type, 'employer'::stakeholder_role,
  '2026-04-14T09:00:00Z'::timestamptz, 'Workplace adjustments implemented', 'e0000000-0000-0000-0000-000000000009',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000027');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'The desk moved and that has helped. I have not received written instructions from my manager at any point. Start time is still 09:00 and nobody has mentioned changing it. Not sure who to ask without it becoming a thing.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-04-29T09:00:00Z'::timestamptz, 'Written instructions have not started', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000028');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Course deadline and quarter end in the same fortnight. Sleeping badly again. Have stopped going to the quiet room because I cannot spare the twenty minutes.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-05-04T09:00:00Z'::timestamptz, 'Running on empty', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000029');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Presentation notably flatter than previous sessions. Reports withdrawal from all restorative activity. Raised concern regarding autistic burnout rather than anxiety relapse. Recommended GP review.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Session — escalating depletion', 'e0000000-0000-0000-0000-000000000003',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000030');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Presents exhausted, cognitively slowed, tearful. Two weeks medical leave certified. Advised phased return thereafter. No medication change at this point.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-05-14T09:00:00Z'::timestamptz, 'Consultation and fit note', 'e0000000-0000-0000-0000-000000000007',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000031');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Cannot face the commute. Missed two days. Everything is loud and I am not managing conversations at work. Sleeping badly. I do not want to write these entries at the moment.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-05-16T09:00:00Z'::timestamptz, 'Worst week so far', 'e0000000-0000-0000-0000-000000000001',
  'high'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000032');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Reviewed in context of current presentation. Assessment favours autistic burnout over anxiety relapse; medication increase not indicated. Sertraline continued at existing dose. Recommendation is load reduction, not pharmacological change.',
  'professional_reported'::source_type, 'psychiatrist'::stakeholder_role,
  '2026-06-04T09:00:00Z'::timestamptz, 'Medication review', 'e0000000-0000-0000-0000-000000000004',
  'restricted'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000033');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Some improvement in sleep. Still fatigued. Leave extended by four weeks with phased return from 21 July at three days per week.',
  'professional_reported'::source_type, 'gp'::stakeholder_role,
  '2026-06-19T09:00:00Z'::timestamptz, 'Follow-up', 'e0000000-0000-0000-0000-000000000007',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000034');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Employer notified of extended leave and phased return date. Course provider notified; two assignment deadlines deferred to September. No contact from subject during this period; all arrangements made via professionals.',
  'professional_reported'::source_type, 'coordinator'::stakeholder_role,
  '2026-06-27T09:00:00Z'::timestamptz, 'Coordination note', 'e0000000-0000-0000-0000-000000000008',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000035');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Return to work at three days per week from today. Staggered start time of 10:00 now active. Written instructions process agreed with line manager and commencing this week.',
  'professional_reported'::source_type, 'employer'::stakeholder_role,
  '2026-07-21T09:00:00Z'::timestamptz, 'Phased return commenced', 'e0000000-0000-0000-0000-000000000009',
  'low'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000036');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Back at work three days a week since the 21st. Have not written anything here for a while. Some days have been fine and some have not, but I stopped keeping track of which.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-07-28T09:00:00Z'::timestamptz, 'Starting to log again', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000037');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'support'::record_domain, 'Tried noise-cancelling headphones for the whole commute for a fortnight. Stopping. Taking the sound away made it harder to judge where people were. Nearly went down the stairs twice.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-08-11T09:00:00Z'::timestamptz, 'Headphones did not work', 'e0000000-0000-0000-0000-000000000001',
  'moderate'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000038');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'workplace'::record_domain, 'Manager has been sending a short written list each morning since the return. It is working. The 10am start is the bigger thing though. The metro at 10 is a different world.',
  'self_reported'::source_type, 'patient'::stakeholder_role,
  '2026-08-18T09:00:00Z'::timestamptz, 'Written instructions are actually happening', 'e0000000-0000-0000-0000-000000000001',
  'low'::sensitivity_level, 'subject_confirmed'::validation_status, 0.75, null, null, 'f0000000-0000-0000-0000-000000000039');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'functional'::record_domain, 'Across entries from February to April 2026, difficulty on the morning commute was reported more often on days following a recorded late finish. This is a pattern in the record, not a confirmed relationship, and the May to July gap means it has not been tested since.',
  'ai_derived'::source_type, 'system'::stakeholder_role,
  '2026-08-20T09:00:00Z'::timestamptz, 'Possible association between late finishes and next-day commute difficulty', null,
  'moderate'::sensitivity_level, 'unvalidated'::validation_status, 0.5, null, null, 'f0000000-0000-0000-0000-000000000040');
select orca_write_record(
  'aaaaaaaa-0000-0000-0000-00000000000a', 'clinical'::record_domain, 'Markedly improved from May presentation. Attributes improvement primarily to the staggered start rather than to any clinical change. Cautious about increasing days back to five before October.',
  'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-08-26T09:00:00Z'::timestamptz, 'Session — post-return review', 'e0000000-0000-0000-0000-000000000003',
  'high'::sensitivity_level, 'professional_validated'::validation_status, 0.9, null, null, 'f0000000-0000-0000-0000-000000000041');

-- The correction, through orca_supersede so both links and both is_current
-- flags move together. R007 stays readable: it was the best reading available
-- after one assessment, and a record that loses its earlier version cannot
-- show anyone how the understanding actually developed.
select orca_supersede('f0000000-0000-0000-0000-000000000007', 'f0000000-0000-0000-0000-000000000024');

-- The other four subjects, thin by instruction, with the stakeholders the
-- roster assigns them so cross-subject access can be tested honestly.
insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000b', 'e0000000-0000-0000-0000-000000000007', 'gp', 'care', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'functional'::record_domain,
  'Caseload placeholder 1 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-06T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'personal'::record_domain,
  'Caseload placeholder 2 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-07T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'support'::record_domain,
  'Caseload placeholder 3 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-08T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'clinical'::record_domain,
  'Caseload placeholder 4 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'functional'::record_domain,
  'Caseload placeholder 5 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-10T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000b', 'support'::record_domain,
  'Caseload placeholder 6 for Rohan Mehta. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-11T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000c', 'e0000000-0000-0000-0000-000000000005', 'ot', 'support_planning', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'functional'::record_domain,
  'Caseload placeholder 1 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-06T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'personal'::record_domain,
  'Caseload placeholder 2 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-07T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'support'::record_domain,
  'Caseload placeholder 3 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-08T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'clinical'::record_domain,
  'Caseload placeholder 4 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'functional'::record_domain,
  'Caseload placeholder 5 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-10T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000c', 'support'::record_domain,
  'Caseload placeholder 6 for Farida Qureshi. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-11T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000d', 'e0000000-0000-0000-0000-000000000004', 'psychiatrist', 'care', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'functional'::record_domain,
  'Caseload placeholder 1 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-06T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'personal'::record_domain,
  'Caseload placeholder 2 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-07T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'support'::record_domain,
  'Caseload placeholder 3 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-08T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'clinical'::record_domain,
  'Caseload placeholder 4 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'functional'::record_domain,
  'Caseload placeholder 5 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-10T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000d', 'support'::record_domain,
  'Caseload placeholder 6 for Dev Sharma. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-11T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000001', 'patient', 'personal_understanding', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000003', 'psychologist', 'care', '2025-09-01T00:00:00Z'),
  ('aaaaaaaa-0000-0000-0000-00000000000e', 'e0000000-0000-0000-0000-000000000008', 'coordinator', 'coordination', '2025-09-01T00:00:00Z');
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'functional'::record_domain,
  'Caseload placeholder 1 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-02-06T09:00:00Z'::timestamptz, 'Caseload note 1', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'personal'::record_domain,
  'Caseload placeholder 2 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-03-07T09:00:00Z'::timestamptz, 'Caseload note 2', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'support'::record_domain,
  'Caseload placeholder 3 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-04-08T09:00:00Z'::timestamptz, 'Caseload note 3', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'clinical'::record_domain,
  'Caseload placeholder 4 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-05-09T09:00:00Z'::timestamptz, 'Caseload note 4', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'functional'::record_domain,
  'Caseload placeholder 5 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-06-10T09:00:00Z'::timestamptz, 'Caseload note 5', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);
select orca_write_record('aaaaaaaa-0000-0000-0000-00000000000e', 'support'::record_domain,
  'Caseload placeholder 6 for Neha Iyer. Not developed; present so a caseload exists.', 'professional_reported'::source_type, 'psychologist'::stakeholder_role,
  '2026-07-11T09:00:00Z'::timestamptz, 'Caseload note 6', 'e0000000-0000-0000-0000-000000000003',
  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);

commit;
