# -*- coding: utf-8 -*-
"""Builds supabase/seed/ananya_record_set.sql from the authoritative extract.

The first parser written for this file silently dropped two records — R007 and
R024 — because they carry a fourth pipe-delimited field marking the
supersession chain. They were the two most important records in the set. The
count check that caught it runs below on every build, and the build fails
rather than emitting a seed that is quietly two records short.
"""
import re, sys, collections

SRC = '/root/.claude/uploads/738555af-a230-5d22-b6e2-81f18c8bfdc0/fdc2ade6-ananya_record_set.md'
s = open(SRC).read()

# The optional fourth field is what the first attempt missed.
BLOCK = re.compile(
    r'```\n\[R(\d+)\]\s+(\d{4}-\d{2}-\d{2})\s*\|\s*(\w+)\s*\|\s*(\w+)\s*(?:\|\s*([^\n]*?))?\n'
    r'(.*?)\((\w+)\)\s*\|\s*(\w+)\s*\|\s*(\w+)\n(.*?)\n(.*?)\n```', re.S)

recs = []
for m in BLOCK.finditer(s):
    rid, date, dom, sen, note, who, role, src, val, title, content = m.groups()
    recs.append(dict(rid=int(rid), date=date, dom=dom, sen=sen, note=(note or '').strip(),
                     who=who.strip(), role=role, src=src, val=val,
                     title=title.strip(), content=' '.join(content.split())))

declared = sorted({int(x) for x in re.findall(r'\[R(\d+)\]', s)})
got = sorted(r['rid'] for r in recs)
if got != declared:
    print('PARSE FAILED — records in the file that were not parsed:',
          sorted(set(declared) - set(got)))
    sys.exit(1)
print(f'parsed {len(recs)} records, ids R{min(got):03d}–R{max(got):03d}, none dropped')

print('  months:', dict(sorted(collections.Counter(r["date"][:7] for r in recs).items())))
print('  domains:', dict(collections.Counter(r['dom'] for r in recs)))
print('  sensitivity:', dict(collections.Counter(r['sen'] for r in recs)))
print('  roles:', dict(collections.Counter(r['role'] for r in recs)))

# supersession, read from the fourth field rather than assumed
sup = {}
for r in recs:
    m = re.match(r'SUPERSEDES R(\d+)', r['note'], re.I)
    if m: sup[r['rid']] = int(m.group(1))
print('  supersession chains:', {f'R{k:03d}': f'R{v:03d}' for k, v in sup.items()})

gap = [r for r in recs if '2026-05-17' <= r['date'] <= '2026-07-27']
print(f'  gap window 17 May–27 Jul: {len(gap)} records, '
      f'{sum(1 for r in gap if r["src"] == "self_reported")} self-reported')

# ------------------------------------------------------------------- emit
def q(v):
    if v is None: return 'null'
    if isinstance(v, list):
        return "array[" + ",".join("'" + x.replace("'","''") + "'" for x in v) + "]::text[]" if v else 'null'
    return "'" + str(v).replace("'", "''") + "'"

S = 'aaaaaaaa-0000-0000-0000-00000000000a'
U = {'patient':'e0000000-0000-0000-0000-000000000001',
     'trusted_person':'e0000000-0000-0000-0000-000000000002',
     'psychologist':'e0000000-0000-0000-0000-000000000003',
     'psychiatrist':'e0000000-0000-0000-0000-000000000004',
     'ot':'e0000000-0000-0000-0000-000000000005',
     'therapist':'e0000000-0000-0000-0000-000000000006',
     'gp':'e0000000-0000-0000-0000-000000000007',
     'coordinator':'e0000000-0000-0000-0000-000000000008',
     'employer':'e0000000-0000-0000-0000-000000000009',
     'university':'e0000000-0000-0000-0000-00000000000a',
     'admin':'e0000000-0000-0000-0000-00000000000b',
     'system': None}
iid = lambda n: 'f0000000-0000-0000-0000-%012d' % n
EV = {'professional_validated':0.9,'subject_confirmed':0.75,'unvalidated':0.5,'outdated':0.4}

O=[]; w=O.append
w("-- Ananya Rao — longitudinal record extract, seeded verbatim.")
w("--")
w("-- GENERATED by scripts/build_record_set.py from the authoritative extract.")
w("-- Edit the extract and regenerate; do not edit this file.")
w("--")
w("-- 41 records, September 2025 to August 2026. All fictional.")
w("--")
w("-- The build refuses to emit unless every [Rnnn] in the source is parsed. The")
w("-- first parser written for it dropped R007 and R024 — the two carrying the")
w("-- supersession chain, because they have a fourth pipe-delimited field — and")
w("-- would have produced a seed that looked complete and was missing exactly")
w("-- the records the dataset exists to demonstrate.")
w("--")
w("-- Relationship dates bind: the roster below is what makes an employer unable")
w("-- to read anything before March 2026, whatever domain it sits in.")
w("")
w("begin;")
w("")
w("delete from context_briefs where subject_id = %s;" % q(S))
w("delete from agents_run where run_id in (select run_id from runs where subject_id = %s);" % q(S))
w("delete from support_outcomes; delete from support_strategies;")
w("delete from files; delete from consents;")
w("delete from record_items where subject_id in (select subject_id from subjects")
w("  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));")
w("delete from stakeholder_relationships where subject_id in (select subject_id from subjects")
w("  where display_name in ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer'));")
w("delete from subjects where display_name in")
w("  ('Ananya Rao','Rohan Mehta','Farida Qureshi','Dev Sharma','Neha Iyer');")
w("delete from users where email like '%@orca.example';")
w("")

SUBJ=[(S,'Ananya Rao','1997-03-14'),
      ('aaaaaaaa-0000-0000-0000-00000000000b','Rohan Mehta','1994-08-02'),
      ('aaaaaaaa-0000-0000-0000-00000000000c','Farida Qureshi','1999-01-27'),
      ('aaaaaaaa-0000-0000-0000-00000000000d','Dev Sharma','1991-11-09'),
      ('aaaaaaaa-0000-0000-0000-00000000000e','Neha Iyer','2001-06-21')]
w("insert into subjects (subject_id, display_name, date_of_birth) values")
w(",\n".join("  (%s, %s, %s)" % (q(a),q(b),q(c)) for a,b,c in SUBJ) + ";")
w("")
# Emails written out rather than derived from the surname. Three of the eleven
# are Raos — Ananya, her sister Divya, and her GP Vikram — so a derived address
# collided on the unique index. A naming rule that works for most of a cast and
# fails for the family is the wrong rule.
PEOPLE=[('patient','Ananya Rao','ananya.rao@orca.example'),
 ('trusted_person','Divya Rao','divya.rao@orca.example'),
 ('psychologist','Dr Kavita Nair','kavita.nair@orca.example'),
 ('psychiatrist','Dr Arun Deshpande','arun.deshpande@orca.example'),
 ('ot','Sana Kulkarni','sana.kulkarni@orca.example'),
 ('therapist','Meera Joshi','meera.joshi@orca.example'),
 ('gp','Dr Vikram Rao','vikram.rao@orca.example'),
 ('coordinator','Priya Salvi','priya.salvi@orca.example'),
 ('employer','Anil Fernandes','anil.fernandes@orca.example'),
 ('university','Ruth Menon','ruth.menon@orca.example'),
 ('admin','Tejas Bhatt','tejas.bhatt@orca.example')]
w("insert into users (user_id, full_name, email, primary_role) values")
w(",\n".join("  (%s, %s, %s, %s)" % (q(U[r]), q(n), q(e), q(r)) for r,n,e in PEOPLE) + ";")
w("")
w("-- Valid-from dates taken from the roster. These are not decoration: they are")
w("-- the floor orca_access_floor applies, and they are why Meera Joshi cannot")
w("-- see anything before February 2026 and Anil Fernandes nothing before March.")
REL=[('patient','2025-09-01','personal_understanding'),('trusted_person','2025-09-01','personal_understanding'),
 ('gp','2025-09-01','care'),('admin','2025-09-01','coordination'),
 ('psychologist','2025-09-15','care'),('ot','2025-10-05','support_planning'),
 ('psychiatrist','2025-11-10','care'),('coordinator','2025-12-01','coordination'),
 ('university','2026-01-05','accommodation'),('therapist','2026-02-10','support_planning'),
 ('employer','2026-03-01','accommodation')]
w("insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values")
w(",\n".join("  (%s, %s, %s, %s, %s)" % (q(S),q(U[r]),q(r),q(p),q(d+'T00:00:00Z')) for r,d,p in REL) + ";")
w("")
w("-- Consents C1–C7, as filed. None withdrawn.")
CONS=[('psychologist',['clinical','functional','personal','support'],'care','2025-09-15'),
 ('psychiatrist',['clinical','functional'],'care','2025-11-10'),
 ('ot',['functional','support'],'support_planning','2025-10-05'),
 ('therapist',['functional','support'],'support_planning','2026-02-10'),
 ('trusted_person',['personal','support'],'personal_understanding','2025-09-01'),
 ('university',['education','functional'],'accommodation','2026-01-05'),
 ('employer',['workplace','functional'],'accommodation','2026-03-01')]
rows=[]
for role,doms,pur,d in CONS:
    for dom in doms:
        rows.append("  (%s, %s, %s::record_domain, %s::purpose_type, %s)" % (q(S),q(U[role]),q(dom),q(pur),q(d)))
w("insert into consents (subject_id, user_id, domain, purpose, granted_on) values")
w(",\n".join(rows) + ";")
w("")
w("-- ------------------------------------------------------ the 41 records")
for r in recs:
    w("select orca_write_record(")
    w("  %s, %s::record_domain, %s," % (q(S), q(r['dom']), q(r['content'])))
    w("  %s::source_type, %s::stakeholder_role," % (q(r['src']), q(r['role'])))
    w("  %s::timestamptz, %s, %s," % (q(r['date']+'T09:00:00Z'), q(r['title']), q(U.get(r['role']))))
    w("  %s::sensitivity_level, %s::validation_status, %s, null, null, %s);"
      % (q(r['sen']), q(r['val']), EV.get(r['val'], 0.5), q(iid(r['rid']))))
w("")
w("-- The correction, through orca_supersede so both links and both is_current")
w("-- flags move together. R007 stays readable: it was the best reading available")
w("-- after one assessment, and a record that loses its earlier version cannot")
w("-- show anyone how the understanding actually developed.")
for new, old in sup.items():
    w("select orca_supersede(%s, %s);" % (q(iid(old)), q(iid(new))))
w("")
w("-- The other four subjects, thin by instruction, with the stakeholders the")
w("-- roster assigns them so cross-subject access can be tested honestly.")
CASELOAD=[('aaaaaaaa-0000-0000-0000-00000000000b','Rohan Mehta',['psychologist','gp']),
 ('aaaaaaaa-0000-0000-0000-00000000000c','Farida Qureshi',['psychologist','ot']),
 ('aaaaaaaa-0000-0000-0000-00000000000d','Dev Sharma',['psychologist','psychiatrist']),
 ('aaaaaaaa-0000-0000-0000-00000000000e','Neha Iyer',['psychologist','coordinator'])]
DOMS=['functional','personal','support','clinical','functional','support','personal']
for sid,name,roles in CASELOAD:
    w("insert into stakeholder_relationships (subject_id, user_id, role, purpose, valid_from) values")
    parts=["  (%s, %s, 'patient', 'personal_understanding', '2025-09-01T00:00:00Z')" % (q(sid), q(U['patient']))]
    for role in roles:
        pur = 'care' if role in ('psychologist','gp','psychiatrist') else \
              ('coordination' if role=='coordinator' else 'support_planning')
        parts.append("  (%s, %s, %s, %s, '2025-09-01T00:00:00Z')" % (q(sid), q(U[role]), q(role), q(pur)))
    w(",\n".join(parts) + ";")
    for i in range(6):
        d='2026-%02d-%02d' % (2+i, 6+i)
        w("select orca_write_record(%s, %s::record_domain," % (q(sid), q(DOMS[i])))
        w("  %s, 'professional_reported'::source_type, 'psychologist'::stakeholder_role," %
          q('Caseload placeholder %d for %s. Not developed; present so a caseload exists.' % (i+1, name)))
        w("  %s::timestamptz, %s, %s," % (q(d+'T09:00:00Z'), q('Caseload note %d'%(i+1)), q(U['psychologist'])))
        w("  'moderate'::sensitivity_level, 'professional_validated'::validation_status, 0.5, null, null, null);")
    w("")
w("commit;")
open('supabase/seed/ananya_record_set.sql','w').write("\n".join(O)+"\n")
print('\nwrote supabase/seed/ananya_record_set.sql (%d lines)' % len(O))
